void test_ttree () {
    TStopwatch t;
    t.Start();
    //read the Tree generated by tree1w and fill two histograms
    //note that we use "new" to create the TFile and TTree objects !
    //because we want to keep these objects alive when we leave this function.
    TFile *f = TFile::Open("root://eospublic.cern.ch//eos/opendata/cms/derived-data/AOD2NanoAODOutreachTool/Run2012BC_DoubleMuParked_Muons.root");
    TTree *t1 = (TTree*)f->Get("Events");
    UInt_t nMuon;
    t1->SetBranchStatus("*",0);
    t1->SetBranchStatus("nMuon",1);
    t1->SetBranchAddress("nMuon",&nMuon);

    // Loop over entries and std::accumulate
    // std::vector<int> nMuon_vec;

    // //read all entries and fill the histograms
    // Long64_t nentries = t1->GetEntries();
    // for (Long64_t i=0;i<nentries;i++) {
    //     t1->GetEntry(i);
    //     nMuon_vec.push_back(nMuon);
    // }

    // auto nMuon_mean = std::accumulate(std::begin(nMuon_vec), std::end(nMuon_vec), 0.0) / std::size(nMuon_vec);

    // Draw histogram and get mean
    t1->Draw("nMuon>>h_nMuon");
    TH1F *h_nMuon = (TH1F*)gDirectory->Get("h_nMuon");
    auto nMuon_mean = h_nMuon->GetMean(); 

    std::cout << nMuon_mean << std::endl;
    t.Stop();
    t.Print();
}